<?php
namespace App\Form;

use App\Form\InputFilter\AtividadeFilter;
use Zend\Form\Element\Hidden;
use Zend\Form\Element\Text;
use Zend\Form\Element\Textarea;
use Zend\Form\Form;

class AtividadeForm extends Form
{
    /**
     * @param  null|int|string $name Optional name for the element
     * @param  array $options Optional options for the element
     */
    public function __construct($name = null, $options = array())
    {
        parent::__construct('atividade', $options); // TODO: Change the autogenerated stub
        $id = new Hidden('id');
        $this->add ( $id );

        $indice = new Hidden('indice');
        $this->add ($indice);

        $this->setInputFilter(new AtividadeFilter());

        $titulo = new Text( 'titulo' );
        $titulo->setLabel ( 'Título: ' )->setLabelAttributes ( array (
            'class' => 'control-label required'
        ) )->setAttributes ( array (
            'class' => 'tool_tip',
            'data-placement' => 'bottom',
            'placeholder' => 'Título da atividade',
            'title' => 'Título da atividade',
            'id' => 'titulo-atividade',
            'maxlength' => '150'
        ) );
        $this->add ( $titulo );

        $descricao = new Textarea( 'descricao' );
        $descricao->setLabel ( 'Descrição:' )->setLabelAttributes ( array (
            'class' => 'control-label required'
        ) )->setAttributes ( array (
            'placeholder' => 'Descrição da atividade',
            'class' => 'jmce tool_tip'
        ) );
        $this->add ( $descricao );
    }
}