<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'EnderecoApi\Module'                 => __DIR__ . '/Module.php',
    'EnderecoApiTest\Framework\TestCase' => __DIR__ . '/tests/EnderecoApiTest/Framework/TestCase.php',
    'EnderecoApiTest\SampleTest'         => __DIR__ . '/tests/EnderecoApiTest/SampleTest.php',
);
