<?php $this->headScript()->prependFile($this->basePath() . '/js/atividade-crud.js')
    ->prependFile($this->basePath() . '/js/jquery.validate.js') ?>

<?php
$form = $this->form;
$fieldset = $form;
$form->setAttribute(
    'action', $this->url('atividade/default',
    array('action' => $this->action,'id' => $this->id)
));

$this->form->prepare();
?>

<div class="ttoolbar">
    <ul id="mapa">
        <li class="first"></li>
        <li class="iten">
            <a href="<?php echo $this->url('home')?>" title="Página Inicial">Página Inicial</a>
        </li>
        <li class="separator"></li>
        <li class="iten">
            <a href="<?php echo $this->url('atividade')?>" title="Lista de Atividades">Lista de Atividades</a>
        </li>
        <li class="separator"></li>
        <li class="iten">
            <span title="Atividade">Atividade (cód: <?php echo $this->id ?>)</span>
        </li>
    </ul>
    <div class="buttons_toolbar">
        <a id="back" href="<?php echo $this->url('atividade') ?>" class="ico_back" title="Voltar"></a>
        <a id="save" class="ico_save" title="Salvar"></a>
    </div>
</div>

<?php echo $this->alertMessage(); ?>

<div class="form_container">
    <?php echo $this->form()->openTag($form) ?>
    <div class="box">
        <div class="box_header">
			<span class="icon">
				<i class="icon-align-justify"></i>
			</span>
            <span class="title">Atividade</span>
        </div>
        <div class="box_content">

            <?php echo $this->formHidden($fieldset->get('id')) ?>
            <?php echo $this->formHidden($fieldset->get('indice')) ?>

            <div class="control-group">
                <?php echo $this->formlabel($fieldset->get('titulo')) ?>
                <div class="controls">
                    <?php echo $this->formInput($fieldset->get('titulo')) ?>
                    <?php echo $this->formElementErrors($fieldset->get('titulo')); ?>
                </div>
            </div>

            <div class="control-group">
                <?php echo $this->formlabel($fieldset->get('descricao')) ?>
                <div class="controls">
                    <?php echo $this->formTextarea($fieldset->get('descricao')) ?>
                    <?php echo $this->formElementErrors($fieldset->get('descricao')); ?>
                </div>
            </div>

            <div class="control-group success">
                <label class="control-label required" for="titulo-noticia" aria-required="true">Título: </label>            <div class="controls">
                    <input type="text" name="noticia[titulo]" class="tool_tip valid" data-placement="bottom" placeholder="Título da notícia" id="titulo-noticia" maxlength="150" value="Dia dos animais" data-original-title="Título da notícia" aria-required="true" aria-invalid="false"><label for="titulo-noticia" class="error valid" style="display: block;">OK!</label>                            </div>
            </div>

        </div>
    </div>
    <?php echo $this->form()->closeTag() ?>
</div>